version: '3.6'

services:
  react:
    image: tigerpath
    command: bash -c "cd frontend && npm start"
    ports:
      - 3000:3000
    volumes:
      - tigerpath-volume:/opt/tigerpath
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - tigerpath-volume:/opt/tigerpath

volumes:
  tigerpath-volume: {}